apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  labels:
    app: feedback-service
spec:
  type: LoadBalancer
  selector:
    app: feedback-service
  ports:
    - protocol: TCP
      port: 8080       # external port
      targetPort: 8080 # container port